version: '3.1'
services:

  mongo:
    image: mongo:4.1
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - mongo:/data/db
    networks:
      main:
        aliases: ['mongo']

  rest:
    image: paua/sensorik-rest:latest
    restart: always
    environment:
      rest_monogo_host: mongo
      rest_monogo_port: 27017
      rest_monogo_db: "bigChart"
      rest_port: 8080
      ENV: "PROD"
    ports:
      - 8080:8080
    networks:
      main:
        aliases: ['rest']

  fill_db:
    image: paua/sensorik-fill_db:latest
    restart: always
    environment:
      fill_monogo_host: mongo
      fill_monogo_port: 27017
      fill_monogo_db: "bigChart"
      fill_website_port: 3000
      ENV: "PROD"
    ports:
      - 3000:3000
    networks:
      main:
        aliases: ['fill_db']
      
  iot_chart:
    image: paua/sensorik-iot_chart:latest
    restart: always
    environment:
      ENV: "PROD"
    ports:
      - 4200:4200
    networks:
      main:
        aliases: ['iot_chart']
volumes:
  mongo:

networks:
  main:
